export const icons = {
  cast: require('./files/icons/cast.svg'),
  check: require('./files/icons/check.svg'),
  chevronRight: require('./files/icons/chevron-right.svg'),
  chevronLeft: require('./files/icons/chevron-left.svg'),
  chevronUp: require('./files/icons/chevron-up.svg'),
  chevronDown: require('./files/icons/chevron-down.svg'),
  cog: require('./files/icons/cog.svg'),
  computer: require('./files/icons/computer.svg'),
  eyeClosed: require('./files/icons/eye-close.svg'),
  google: require('./files/icons/google.svg'),
  logOut: require('./files/icons/log-out.svg'),
  messages: require('./files/icons/messages.svg'),
  phone: require('./files/icons/phone.svg'),
  search: require('./files/icons/search.svg'),
  starFull: require('./files/icons/star-full.svg'),
  star: require('./files/icons/star.svg'),
  userCircle: require('./files/icons/user-circle.svg'),
  addUser: require('./files/icons/user-plus.svg'),
  removeUser: require('./files/icons/user-remove.svg'),
  user: require('./files/icons/user.svg'),
  mute: require('./files/icons/volume-mute.svg'),
};
